# GitHub renders a "Sponsor" button from this file.
github: [didrod205]
custom: ["https://elab-studio.lemonsqueezy.com/checkout/buy/5d059b89-51d0-456b-b33a-ed56994f7010"]

# Uncomment and fill in once you create the accounts:
# ko_fi: yourname
# buy_me_a_coffee: yourname
